{
 "title": "Brocade: Port Performance Details",
 "tags": [ "Brocade" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.stats.ports.*" },
   { "name": "Switch", "query": "brocade.stats.ports.$Fabric.*" },
   {
    "name": "Porttype",
    "query": "brocade.stats.ports.$Fabric.$Switch.*"
   },
   {
    "name": "Slot",
    "query": "brocade.stats.ports.$Fabric.$Switch.$Porttype.*"
   },
   {
    "name": "Port",
    "query": "brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.*"
   },
   {
    "name": "RXTX",
    "query": "brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.*.timeseriestraffic.*"
   }
  ]
 },
 "panels": [
  { "title": "Aggregated Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Porttraffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(sortByMaxima(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriestraffic.rx)), 'RX')"
    },
    {
     "target": "alias(sumSeries(sortByMaxima(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriestraffic.tx)), 'TX')"
    }
   ]
  },
  { "title": "Performance Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Portutilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesutilpercentage.$RXTX), 3, 4, 5, 6, 7, 9)"
    }
   ]
  },
  {
   "title": "Porttraffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriestraffic.$RXTX), 3, 4, 5, 6, 7, 9)"
    }
   ]
  }
 ]
}