{
 "title": "Brocade: Initiator Overview",
 "tags": [
  "Brocade",
  "BETA"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "brocade.stats.hosts.initiator.*.*"
   }
  ]
 },
 "panels": [
  { "title": "Initiator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RX Throughput for HBAs of $Host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriestraffic.rx), 4, 5, 6, 8)"
    }
   ]
  },
  {
   "title": "TX Throughput for HBAs of $Host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriestraffic.tx), 4, 5, 6, 8)"
    }
   ]
  },
  {
   "title": "RX Utilization for HBAs of $Host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesutilpercentage.rx), 4, 5, 6, 8)"
    }
   ]
  },
  {
   "title": "TX Utilization for HBAs of $Host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesutilpercentage.tx), 4, 5, 6, 8)"
    }
   ]
  },
  { "title": "Initator Error Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Link Resets",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.initiator.*.$Host.*.timeserieslinkresets.*), 'sum')"
    }
   ]
  },
  {
   "title": "Total Link Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.initiator.*.$Host.*.{timeserieslinkfailures,timeseriessignallosses,timeseriessynclosses}), 'sum')"
    }
   ]
  },
  {
   "title": "Total Pyhiscal Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.initiator.*.$Host.*.{timeseriescrcerrors,timeseriesencodeerrorout,timeseriesinvalidorderedsets,timeseriesinvalidtransmissions,timeseriessequenceerrors}), 'sum')"
    }
   ]
  },
  {
   "title": "Total Discards",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.initiator.*.$Host.*.timeseriesc3discards), 'sum')"
    }
   ]
  },
  {
   "title": "Initiator Link Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Resets for $Host",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeserieslinkresets.*), 4, 5, 6, 7,8)"
      }
     ]
    },
    {
     "title": "Link Failure for $Host",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeserieslinkfailures), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss of Signal for $Host",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriessignallosses), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss of Sync for $Host",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriessynclosses), 4, 5, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Initiator Pyhsical Erros",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CRC Errors for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriescrcerrors), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Encoding Out Errors for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesencodeerrorout), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Ordered Set for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesinvalidorderedsets), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Transmission Word for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesinvalidtransmissions), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Sequence Errors for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriessequenceerrors), 4, 5, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Initiator Discards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Discards for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesc3discards), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Other Discards for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesc3discardsother), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "RX Timeout Discards for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesc3discardsrxto), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "TX Timeout Discards for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesc3discardstxto), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Destination Unreachable Discards for $Host",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.initiator.*.$Host.*.timeseriesc3discardsunreachable), 4, 5, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Initiator SFP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "SFP TX Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.stats.hosts.initiator.*.$Host.*.timeseriessfppower.txp, 4, 5, 6)"
      }
     ]
    },
    {
     "title": "SFP RX Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.stats.hosts.initiator.*.$Host.*.timeseriessfppower.rxp, 4, 5, 6)"
      }
     ]
    }
   ]
  }
 ]
}