{
 "title": "Brocade: Migration",
 "tags": [
  "Brocade",
  "Migration"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Fabric 1 - X6-8 / DCX Kopplung", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "E-Port  Throughput Chassis 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.5.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.5.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.6.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.6.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.9.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.9.*.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "E-Port  Throughput Chassis 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.5.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.5.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.6.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.6.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.9.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.9.*.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "E-Port  Utilization Chassis 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.5.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.5.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.6.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.6.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.9.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.9.*.timeseriesutilpercentage.tx"
    }
   ]
  },
  {
   "title": "E-Port  Utilization Chassis 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.5.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.5.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.6.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.6.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.9.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.9.*.timeseriesutilpercentage.tx"
    }
   ]
  },
  { "title": "Fabric 2 - X6-8 / DCX Kopplung", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "E-Port  Throughput Chassis 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.5.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.5.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.6.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.6.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.9.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.9.*.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "E-Port  Throughput Chassis 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.5.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.5.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.6.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.6.*.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.9.*.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.9.*.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "E-Port  Utilization Chassis 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.5.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.5.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.6.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.6.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.9.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.9.*.timeseriesutilpercentage.tx"
    }
   ]
  },
  {
   "title": "E-Port  Utilization Chassis 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.5.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.5.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.6.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.6.*.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.9.*.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.9.*.timeseriesutilpercentage.tx"
    }
   ]
  },
  {
   "title": "Fabric 1 - RZ Kopplung FR1 <=> FBE",
   "type": "row",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "FR1 E-Port Link Throughput Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.4.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.4.0.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "FBE E-Port Link Throughput Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.0.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "FR1 E-Port Utilization Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-1.E_PORT.4.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFHFFC01-2.E_PORT.4.0.timeseriesutilpercentage.tx"
    }
   ]
  },
  {
   "title": "FBE E-Port Utilization Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-1.E_PORT.4.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric1.DFRFFC01-2.E_PORT.4.0.timeseriesutilpercentage.tx"
    }
   ]
  },
  {
   "title": "Fabric 2 - RZ Kopplung FR1 <=> FBE",
   "type": "row",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "FR1 E-Port Link Throughput Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.4.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.4.0.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "FBE E-Port Link Throughput Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.3.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.3.0.timeseriestraffic.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.0.timeseriestraffic.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.0.timeseriestraffic.tx"
    }
   ]
  },
  {
   "title": "FR1 E-Port Utilization Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-1.E_PORT.4.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFHFFC02-2.E_PORT.4.0.timeseriesutilpercentage.tx"
    }
   ]
  },
  {
   "title": "FBE E-Port Utilization Chassis 1 + 2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-1.E_PORT.4.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.3.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.3.0.timeseriesutilpercentage.tx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.0.timeseriesutilpercentage.rx"
    },
    {
     "target": "brocade.stats.ports.Fabric2.DFRFFC02-2.E_PORT.4.0.timeseriesutilpercentage.tx"
    }
   ]
  }
 ]
}