{
 "title": "Brocade: SFP Statistics",
 "tags": [
  "Brocade",
  "Beta"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.stats.ports.*" },
   {
    "name": "Density",
    "label": "Density-Limit (dB)",
    "query": "-1.0,-2.0,-3.0,-4.0,-5.0,-6.0,-7.0,-8.0,-9.0,-10.0,-11.0,-12.0,-13.0,-14.0"
   }
  ]
 },
 "panels": [
  { "title": "E-Ports", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "E-Port TX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(sortByMaxima(brocade.stats.ports.$Fabric.*.*E_PORT.[01234569].*.timeseriessfppower.txp), $Density)), 4, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "E-Port RX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(sortByMaxima(brocade.stats.ports.$Fabric.*.*E_PORT.[01234569].*.timeseriessfppower.rxp), $Density)), 4, 5, 6, 7)"
    }
   ]
  },
  { "title": "F-Ports", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "F-Port TX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(sortByMaxima(brocade.stats.ports.$Fabric.*.F_PORT.*.*.timeseriessfppower.txp), $Density)), 4, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "F-Port RX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(sortByMaxima(brocade.stats.ports.$Fabric.*.F_PORT.*.*.timeseriessfppower.rxp), $Density)), 4, 5, 6, 7)"
    }
   ]
  },
  { "title": "Storage Ports", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "F-Port TX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(brocade.stats.hosts.target.$Fabric.*.*.timeseriessfppower.txp, $Density)), 5, 6)"
    }
   ]
  },
  {
   "title": "F-Port RX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(brocade.stats.hosts.target.$Fabric.*.*.timeseriessfppower.rxp, $Density)), 5, 6)"
    }
   ]
  },
  { "title": "Server Ports", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "F-Port TX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(brocade.stats.hosts.initiator.$Fabric.*.*.timeseriessfppower.txp, $Density)), 5, 6)"
    }
   ]
  },
  {
   "title": "F-Port RX Power",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(removeEmptySeries(averageBelow(brocade.stats.hosts.initiator.$Fabric.*.*.timeseriessfppower.rxp, $Density)), 5, 6)"
    }
   ]
  }
 ]
}