{
 "title": "Brocade: ISL Status",
 "tags": [
  "Brocade",
  "BETA"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.stats.ports.*" }
  ]
 },
 "panels": [
  {
   "title": "Performance: Long Distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "RX Throughput for Long Distance ISLs of $Fabric",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriestraffic.rx), 4, 6, 7)"
    }
   ]
  },
  {
   "title": "Avg RX Throughput for Long Distance ISLs",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 1 },
   "format": "MBs",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriestraffic.rx)"
    }
   ]
  },
  {
   "title": "TX Throughput for Long Distance ISLs of $Fabric",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriestraffic.tx), 4, 6, 7)"
    }
   ]
  },
  {
   "title": "Avg TX Throughput for Long Distance ISLs",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "format": "MBs",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriestraffic.tx)"
    }
   ]
  },
  {
   "title": "RX Utilization for Long Distance ISLs of $Fabric",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesutilpercentage.rx), 4, 6, 7)"
    }
   ]
  },
  {
   "title": "Avg RX Utilization for Long Distance ISLs",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesutilpercentage.rx)"
    }
   ]
  },
  {
   "title": "TX Utilizartion for Long Distance ISLs of $Fabric",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesutilpercentage.tx), 4, 6, 7)"
    }
   ]
  },
  {
   "title": "Avg TX Throughput for Long Distance ISLs",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesutilpercentage.tx)"
    }
   ]
  },
  {
   "title": "Errors: Long Distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Resets for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeserieslinkresets.*, 20), 4, 6, 7, 9)"
      }
     ]
    },
    {
     "title": "Link Failures for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeserieslinkfailures, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss of Signal for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriessignallosses, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss os Sync for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriessynclosses, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesc3discards, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Other C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesc3discardsother, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "TX Timeout C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesc3discardsrxto, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "TX Timeout C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesc3discardstxto, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Destination Unreachable C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesc3discardsunreachable, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Ordered Set for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesinvalidorderedsets, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Transmission Words for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriesinvalidtransmissions, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Sequence Errors for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.LE_PORT.*.*.timeseriessequenceerrors, 20), 4, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Standard Distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Throughput for ISLs of $Fabric",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriestraffic.rx), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Average RX Throughput for ISLs for $Fabric",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 23 },
     "format": "MBs",
     "valueName": "avg",
     "targets": [
      {
       "target": "averageSeries(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriestraffic.rx)"
      }
     ]
    },
    {
     "title": "TX Throughput for ISLs of $Fabric",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriestraffic.tx), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Average TX Throughput for ISLs for $Fabric",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 23 },
     "format": "MBs",
     "valueName": "avg",
     "targets": [
      {
       "target": "averageSeries(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriestraffic.tx)"
      }
     ]
    },
    {
     "title": "RX Utilization for ISLs of $Fabric",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesutilpercentage.rx), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Average RX Utilization for ISLs for $Fabric",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 33 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "target": "averageSeries(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesutilpercentage.rx)"
      }
     ]
    },
    {
     "title": "TX Utilizartion for ISLs of $Fabric",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesutilpercentage.tx), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Average TX Throughput for ISLs for $Fabric",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 33 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "target": "averageSeries(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesutilpercentage.tx)"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors: Standard Distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Resets for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 54 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeserieslinkresets.*, 20), 4, 6, 7, 9)"
      }
     ]
    },
    {
     "title": "Link Failures for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 54 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeserieslinkfailures, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss of Signal for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 54 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriessignallosses, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss os Sync for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 54 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriessynclosses, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 64 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesc3discards, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Other C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 64 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesc3discardsother, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "TX Timeout C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 64 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesc3discardsrxto, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "TX Timeout C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 64 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesc3discardstxto, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Destination Unreachable C3 Discards for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 74 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesc3discardstxto, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Ordered Set for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 74 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesinvalidorderedsets, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Transmission Words for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 74 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriesinvalidtransmissions, 20), 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Sequence Errors for $Fabric",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 74 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(brocade.stats.ports.$Fabric.*.E_PORT.*.*.timeseriessequenceerrors, 20), 4, 6, 7)"
      }
     ]
    }
   ]
  }
 ]
}