{
 "title": "Brocade: Port Error Details",
 "tags": [ "Brocade" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.stats.ports.*" },
   { "name": "Switch", "query": "brocade.stats.ports.$Fabric.*" },
   {
    "name": "Porttype",
    "query": "brocade.stats.ports.$Fabric.$Switch.*"
   },
   {
    "name": "Slot",
    "query": "brocade.stats.ports.$Fabric.$Switch.$Porttype.*"
   },
   {
    "name": "Port",
    "query": "brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.*"
   }
  ]
 },
 "panels": [
  { "title": "Link Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10 Ports with Loss of Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriessignallosses, 10)), 'max'), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Top 10 Ports with Loss of Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriessynclosses, 10)), 'max'), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Top 10 Ports with Link Resets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeserieslinkresets.in, 10)), 'max'), 3, -6, -5, -4, -3, -1)"
    },
    {
     "target": "aliasByNode(consolidateBy(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeserieslinkresets.out, 10)), 'max'), 3, -6, -5, -4, -3, -1)"
    }
   ]
  },
  { "title": "C3 Discards Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top 10 Ports with Discarded C3 Frames",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesc3discards, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  { "title": "C3 Discards Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Top 10 Ports with Discarded C3 Frames (RX Timeout)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesc3discardsrxto, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Top 10 Ports with Discarded C3 Frames (TX Timeout)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesc3discardstxto, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Top 10 Ports with Discarded C3 Frames (other Discards)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesc3discardsother, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Top 10 Ports with Discarded C3 Frames (Destination unreachable)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesc3discardsunreachable, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  { "title": "Pyhsical Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Ports with Encoding Out Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesencodeerrorout, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Ports with Invalid Transmission Word",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesinvalidtransmissions, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Ports with CRC Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriescrcerrors, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  {
   "title": "Invalid Orderd Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(highestAverage(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriesinvalidorderedsets, 10)), 3, -5, -4, -3, -2)"
    }
   ]
  },
  { "title": "SFP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "SFP RX Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "target": "lowestAverage(removeEmptySeries(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriessfppower.rxp), 10)"
    }
   ]
  },
  {
   "title": "SFP TX Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "target": "lowestAverage(removeEmptySeries(brocade.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.timeseriessfppower.txp), 10)"
    }
   ]
  }
 ]
}