{
 "title": "Brocade: Switch Details",
 "tags": [ "Brocade" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.stats.switches.*" },
   {
    "name": "Switch",
    "query": "brocade.stats.switches.$Fabric.*"
   }
  ]
 },
 "panels": [
  { "title": "Switch Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Switch CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.switches.$Fabric.$Switch.timeseriescpuutilpercentage), 3, 4)"
    }
   ]
  },
  {
   "title": "Switch Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.switches.$Fabric.$Switch.timeseriesmemoryutilpercentage), 3, 4)"
    }
   ]
  },
  { "title": "Switch Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Switch Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.switches.$Fabric.$Switch.timeseriestemperature.*), 3, 4, 6)"
    }
   ]
  },
  {
   "title": "FAN RPM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.switches.$Fabric.$Switch.timeseriesfanspeed.*), 3, 4, 6)"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Switch Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima(brocade.stats.switches.$Fabric.$Switch.timeseriessystemuptime), 4)"
    }
   ]
  }
 ]
}