{
 "title": "Brocade: Target Overview",
 "tags": [
  "Brocade",
  "BETA"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Target", "query": "brocade.stats.hosts.target.*.*" }
  ]
 },
 "panels": [
  { "title": "Target Port Performance", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Port RX Thoughput for $Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(brocade.stats.hosts.target.*.$Target.*.timeseriestraffic.rx, 0.1), 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Port TX Thoughput for $Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(brocade.stats.hosts.target.*.$Target.*.timeseriestraffic.tx, 0.1), 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Port RX Utilization for $Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(brocade.stats.hosts.target.*.$Target.*.timeseriesutilpercentage.rx, 0.1), 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Port TX Utilization for $Target",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(maximumAbove(brocade.stats.hosts.target.*.$Target.*.timeseriesutilpercentage.tx, 0.1), 4, 5, 6)"
    }
   ]
  },
  { "title": "Error Overview", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total  Number of Link Resets",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.target.*.$Target.*.timeserieslinkresets.*), 'sum')"
    }
   ]
  },
  {
   "title": "Total  Number of Link Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.target.*.$Target.*.{timeserieslinkfailures,timeseriessignallosses,timeseriessynclosses}), 'sum')"
    }
   ]
  },
  {
   "title": "Total  Number of Phyiscal Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.target.*.$Target.*.{timeseriescrcerrors,timeseriesencodeerrorout,timeseriesinvalidorderedsets,timeseriesinvalidtransmissions,timeseriessequenceerrors}), 'sum')"
    }
   ]
  },
  {
   "title": "Total  Number of Discards",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "target": "consolidateBy(sumSeries(brocade.stats.hosts.target.*.$Target.*.timeseriesc3discards), 'sum')"
    }
   ]
  },
  {
   "title": "Target Link Errors / Resets",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Link Reset for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeserieslinkresets.*), 4, 5, 6, 7,8)"
      }
     ]
    },
    {
     "title": "Link Failures for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeserieslinkfailures), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss of Signal for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriessignallosses), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Loss of Sync for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriessynclosses), 4, 5, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Target Physical Errors",
   "type": "row",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CRC Errors for $Target",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriescrcerrors), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Encoding Out Errors for $Target",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesencodeerrorout), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Ordered Set for $Target",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesinvalidorderedsets), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Invalid Transmission Word for $Target",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesinvalidtransmissions), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Sequence Errors for $Target",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriessequenceerrors), 4, 5, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Target Discards",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Discards for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesc3discards), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Other Discards for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesc3discardsother), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "RX Timeout Discards for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesc3discardsrxto), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "TX Timeout Discards for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesc3discardsrxto), 4, 5, 6, 7)"
      }
     ]
    },
    {
     "title": "Destination Unreachable Discards for $Target",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "target": "aliasByNode(sortByMaxima(brocade.stats.hosts.target.*.$Target.*.timeseriesc3discardsunreachable), 4, 5, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Target SFP Statistics",
   "type": "row",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Target SFP TX Power",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.stats.hosts.target.*.$Target.*.timeseriessfppower.txp, 4, 6)"
      }
     ]
    },
    {
     "title": "$Target SFP RX Power",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.stats.hosts.target.*.$Target.*.timeseriessfppower.rxp, 4, 6)"
      }
     ]
    }
   ]
  }
 ]
}